FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG RUNTIME_IDENTIFIER
WORKDIR /src
COPY . .

RUN apt-get update && apt-get install clang zlib1g-dev -y

# Publish the app with AOT compilation
RUN dotnet publish -c Release -o /app --self-contained true /p:PublishAot=true /p:RuntimeIdentifier=$RUNTIME_IDENTIFIER

FROM mcr.microsoft.com/dotnet/runtime:8.0 AS final
USER app
WORKDIR /app
COPY --from=build /app .
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

ENTRYPOINT ["./WebApi.Performance"]