name: dotnet8 WebApi Performance

on:
  push:
    branches: 
      - 'feature/*'
      - 'fix/*'
    paths:
      - 'src/dotnet8/WebApi.Performance/**'
  pull_request:
    paths:
      - 'src/dotnet8/WebApi.Performance/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release:
          - platform: linux/amd64, linux/arm64
            build-args:
              - APP_UID=0
              - PORT=80
          - platform: linux/amd64, linux/arm64
            build-args:
              - APP_UID=1000
              - PORT=8080
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
          
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}          