name: dotnet8 WebApi Performance

on:
  push:
    paths:
      - 'src/dotnet8/WebApi.Performance/**'
  pull_request:
    paths:
      - 'src/dotnet8/WebApi.Performance/**'

jobs:
  build:
    strategy:
      matrix:
        release:
          - platform: linux/amd64, linux/arm64
            runner: ubuntu-latest
            build-args:
              - APP_UID=0
              - PORT=80
          - platform: linux/amd64, linux/arm64
            runner: ubuntu-latest
            build-args:
              - APP_UID=1000
              - PORT=8080
    runs-on: ${{ matrix.release.runner }}
    permissions:
      contents: read
      packages: write    
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
          
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}   
            
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
          tags: type=raw,value={{date 'YYYYMMDDHHmm'}}-{{sha}}
            
      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          build-args: ${{ matrix.release.build-args }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: src/WebApi.Performance/Dockerfile
          platforms: ${{ matrix.release.platform }}
          provenance: mode=max
          sbom: true
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}            